---
title: "Preliminary results for predicting adverse CDI outcomes"
date: "`r Sys.Date()`"
output: 
  github_document:
    html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

## load data

```{r deps}
library(data.table)
library(here)
library(knitr)
library(tidyverse)

source(here('workflow', 'scripts', 'filter_first_samples.R')) 
```

```{r data}
otu_dat <- read_csv(here('data', 'SraRunTable.csv')) %>% 
              rename(sample_id = sample_title) %>% 
  left_join(fread(here('data', 'mothur', 'cdi.opti_mcc.shared')) %>% 
  rename(Run = Group), by = 'Run')
seq_metadat <- read_tsv(here('data', 'process', 'final_CDI_16S_metadata.tsv')) %>% 
              rename(sample_id = `CDIS_Sample ID`, 
                     subject_id = `CDIS_Study ID`,
                     collection_date = `CDIS_collect date`) %>% 
  full_join(read_csv(here('data', 'process', 'case_idsa_severity.csv')) %>% 
              rename(sample_id = sample,
                     idsa_lab = idsa_severity),
            by = 'sample_id')

attrib_dat <- read_csv(here('data', 'raw', 'mishare', 
                            'clinical_outcomes.csv')) %>% 
  select(-CDIFF_SAMPLE_DATE, -CDIFF_COLLECT_DTM) %>% 
  mutate(chart_reviewed = TRUE)
unattrib_dat <- read_csv(here('data', 'raw', 'mishare', 
                              'clinical_outcomes_pt2.csv'))  %>% 
  select(-CDIFF_SAMPLE_DATE, -CDIFF_COLLECT_DTM) %>% 
  mutate(chart_reviewed = FALSE) 
metadat <- bind_rows(attrib_dat, unattrib_dat) %>% 
  rename(sample_id = SAMPLE_ID, 
         idsa_chart = IDSA_severe,
         attrib = ATTRIB_SEVERECDI,
         unattrib = UNATTRIB_SEVERECDI) %>% 
  select(-SUBJECT_ID) %>% 
  full_join(seq_metadat,
            by = c('sample_id')) %>% 
  filter(!is.na(cdiff_case)) %>% 
  mutate(idsa = case_when(idsa_chart == 1 ~ 'yes',
                          idsa_chart == 0 ~ 'no',
                          TRUE ~ idsa_lab),
         attrib = case_when(attrib == 1 ~ 'yes',
                            attrib == 0 ~ 'no',
                            TRUE ~ NA_character_),
         unattrib = case_when(unattrib == 1 ~ 'yes',
                              unattrib == 0 ~ 'no',
                              TRUE ~ NA_character_),
         allcause = case_when(attrib == 'yes' | unattrib == 'yes' ~ 'yes',
                              attrib == 'no' & unattrib == 'no' ~ 'no',
                              is.na(attrib) ~ unattrib,
                              TRUE ~ NA_character_)
         ) %>% 
  select(sample_id, subject_id, collection_date, cdiff_case, 
         chart_reviewed, idsa, attrib, unattrib, allcause) 
```

```{r filter}
multi_samples <-
  metadat %>% 
  group_by(subject_id) %>% 
  tally() %>% 
  filter(n > 1)

metadat_1s <- filter_first_samples(metadat)
metadat_cases <- metadat_1s %>% filter(cdiff_case == 'Case')
```


## CDI cases

```{r cdi-cases}
metadat %>% group_by(cdiff_case) %>% tally() %>% kable()
```

### excluding longitudinal samples

```{r cdi-cases_one-per-patient}
metadat_1s %>% group_by(cdiff_case) %>% tally() %>% kable()
```


## IDSA severity

```{r idsa}
metadat_cases %>% group_by(idsa) %>% tally() %>% kable()
```

## Attributable severity

```{r attrib}
metadat_cases %>% group_by(attrib) %>% tally() %>% kable()
```


## All-cause severity

```{r allcause}
metadat_cases %>%  group_by(attrib, unattrib, allcause) %>% tally() %>% kable()
metadat_cases %>% group_by(allcause) %>% tally() %>% kable()
```


## idsa x attrib x allcause

```{r sum}
metadat_cases %>% 
  group_by(idsa, attrib, unattrib) %>% 
  tally() %>% kable()
metadat_cases %>% 
  group_by(idsa, allcause) %>% 
  tally() %>% kable()
```

