cluster: "sbatch 
            --job-name {rule}.{wildcards} 
            --account pschloss1
            --partition standard
            --mail-user mlcoden@umich.edu
            --mail-type FAIL
            --nodes 1
            --ntasks {resources.ncores}
            --mem-per-cpu {resources.mem_gb}
            --time {resources.walltime}
            --output log/hpc/jobs/{rule}.{wildcards}.out
          "
jobs: 4999
immediate-submit: False
verbose: true
notemp: true
keep-going: true
latency-wait: 120
use-conda: true
conda-frontend: "mamba"
default-resources:
  - ncores=1
  - mem_gb=1
  - walltime="48:00:00"