name: cdi
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - mothur==1.43.0
  - r==4.0.2
  - r-broom==0.7
  - r-tidyverse==1.3.0
  - r-cowplot==1.0.0
  - r-vegan==2.5_6
  - r-knitr==1.29
  - r-rmarkdown==2.3
  - r-ggpubr==0.4.0
  - r-gganimate==1.0.6
  - r-writexl==1.3
  - r-glue==1.4.1
  - r-ggtext==0.1.0
