dataset1: data/process/ml_CvDC.csv
dataset2: data/process/ml_CvNDC.csv
dataset3: data/process/ml_DCvNDC.csv
outcome_colname: outcome
ml_methods:
 - glmnet
 - rf
 - rpart2
 - svmRadial
kfold: 5
ncores: 36
nseeds: 100
