ml_methods:
 - glmnet
kfold: 5
ncores: 36
nseeds: 20
outcomes:
  - idsa
  - allcause
  - attrib
tax_levels:
  - OTU
  - genus
  - family
  - order
metrics:
  - AUC
train_frac:
  - 0.8
dataset_subsets:
  - int