ml_methods:
 - rf
kfold: 5
ncores: 36
nseeds: 50
outcomes:
  - idsa
  - allcause
  - attrib
tax_levels:
  - asv
  - OTU
  - genus
  - family
  - order
metrics:
  - AUC
train_frac:
  - 0.65
dataset_subsets:
  - int
  - full