name: adverseCDI
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - mothur>=1.46
  - r-base=4
  - r-cowplot
  - r-doFuture
  - r-foreach
  - r-future
  - r-future.apply
  - r-here
  - r-mikropml=1.2.2
  - r-rmarkdown
  - r-rpart
  - r-testthat
  - r-tidyverse>=1.3
  - snakemake>=6.12.3
