name: adverseCDI
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - mothur>=1.46
  - r-base=4
  - r-cowplot
  - r-doFuture
  - r-foreach
  - r-future
  - r-future.apply
  - r-here
  - r-mikropml=1.2.2
  - r-rmarkdown
  - r-rpart
  - r-testthat
  - r-tidyverse>=1.3
<<<<<<< HEAD
  - snakemake=6.12.3
=======
  - snakemake>=6.12
>>>>>>> be66de3d41910857b8c5e55be2cc035996ea977a
