on:
  push:
    paths:
      - _quarto.yml
      - paper/paper.qmd
      - index.qmd

name: Render and Publish

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.3"

      - name: "Install R deps"
        run: |
          install.packages(c("assertthat", "glue", "here", "knitr",
                             "kableExtra", "schtools", "tidyverse"
                            ))
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

